name: Docker
on: [push]
jobs:
  build-awscli-python2.7:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Docker Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -t $DOCKER_USERNAME/aws:python2.7 -f docker/python2.7/Dockerfile .
      - name: Push to Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push $DOCKER_USERNAME/aws:python2.7